package bg.nbu.citb408.onlinegradebook.controller;

import bg.nbu.citb408.onlinegradebook.repositories.UserRepository;
import bg.nbu.citb408.onlinegradebook.constant.RoleType;
import bg.nbu.citb408.onlinegradebook.model.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/users") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path="/create") // Map ONLY POST Requests
    public @ResponseBody String addNewUser(@RequestParam String name
            , @RequestParam String egn, @RequestParam String address, @RequestParam RoleType role) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User newUser = new User();
        newUser.setUsername(name);
        newUser.setEGN(egn);
        newUser.setAddress(address);
        newUser.setRole(role);
        userRepository.save(newUser);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}