export const stundets6a = [
  {
    name: "Andrey Nikolov",
    subjects: {
      0: {
        firstSemester: [5, 6, 4, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [6, 6, 6],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
      1: {
        firstSemester: [6, 5, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [6, 6, 6],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
      2: {
        firstSemester: [4, 4, 5],
        firstSemesterGrade: 4,
        secondSemester: [5, 2, 6],
        secondSemesterGrade: 5,
        finalGrade: 5,
      },
      3: {
        firstSemester: [2, 3, 6, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [2, 2.5, 6, 6, 6],
        secondSemesterGrade: 4.5,
        finalGrade: 5,
      },
      4: {
        firstSemester: [6, 5.2, 5.5, 6],
        firstSemesterGrade: 6,
        secondSemester: [4.5, 5.5, 6, 6, 5.5],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
      5: {
        firstSemester: [6, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [6, 6, 6],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
    },
  },
  {
    name: "Ivan Ivanov",
    subjects: {
      0: {
        firstSemester: [4, 3, 4],
        firstSemesterGrade: 4,
        secondSemester: [5.2, 3, 4],
        secondSemesterGrade: 4,
        finalGrade: 4,
      },
      1: {
        firstSemester: [6, 6],
        firstSemesterGrade: 6,
        secondSemester: [5, 4, 5],
        secondSemesterGrade: 5,
        finalGrade: 5,
      },
      2: {
        firstSemester: [4, 3, 2, 4],
        firstSemesterGrade: 3,
        secondSemester: [5, 2, 6],
        secondSemesterGrade: 4,
        finalGrade: 4,
      },
      3: {
        firstSemester: [6, 2, 3],
        firstSemesterGrade: 4,
        secondSemester: [6, 6, 4],
        secondSemesterGrade: 5,
        finalGrade: 6,
      },
      4: {
        firstSemester: [5.5, 6],
        firstSemesterGrade: 6,
        secondSemester: [4.5, 5.5],
        secondSemesterGrade: 5,
        finalGrade: 5,
      },
      5: {
        firstSemester: [6, 2, 6],
        firstSemesterGrade: 5,
        secondSemester: [6, 2, 6],
        secondSemesterGrade: 4,
        finalGrade: 4,
      },
    },
  },
  {
    name: "Boyko Borisov",
    subjects: {
      0: {
        firstSemester: [2, 3, 2],
        firstSemesterGrade: 2,
        secondSemester: [2, 3, 2],
        secondSemesterGrade: 2,
        finalGrade: 3,
      },
      1: {
        firstSemester: [2, 2.5, 3],
        firstSemesterGrade: 3,
        secondSemester: [3, 4, 2, 2],
        secondSemesterGrade: 2,
        finalGrade: 2,
      },
      2: {
        firstSemester: [2],
        firstSemesterGrade: 2,
        secondSemester: [2],
        secondSemesterGrade: 2,
        finalGrade: 2,
      },
      3: {
        firstSemester: [3],
        firstSemesterGrade: 3,
        secondSemester: [3],
        secondSemesterGrade: 3,
        finalGrade: 3,
      },
      4: {
        firstSemester: [2],
        firstSemesterGrade: 2,
        secondSemester: [2],
        secondSemesterGrade: 2,
        finalGrade: 6,
      },
      5: {
        firstSemester: [3, 3],
        firstSemesterGrade: 3,
        secondSemester: [2, 3],
        secondSemesterGrade: 3,
        finalGrade: 2,
      },
    },
  },
  {
    name: "Pesho Peshov",
    subjects: {
      0: {
        firstSemester: [5, 6, 4, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [6, 6, 6],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
      1: {
        firstSemester: [6, 5, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [6, 6, 6],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
      2: {
        firstSemester: [4, 4, 5],
        firstSemesterGrade: 4,
        secondSemester: [5, 2, 6],
        secondSemesterGrade: 5,
        finalGrade: 5,
      },
      3: {
        firstSemester: [2, 3, 6, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [2, 2.5, 6, 6, 6],
        secondSemesterGrade: 4.5,
        finalGrade: 5,
      },
      4: {
        firstSemester: [6, 5.2, 5.5, 6],
        firstSemesterGrade: 6,
        secondSemester: [4.5, 5.5, 6, 6, 5.5],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
      5: {
        firstSemester: [6, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [6, 6, 6],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
    },
  },
  {
    name: "Gergana Petrova",
    subjects: {
      0: {
        firstSemester: [5, 6, 4, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [6, 6, 6],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
      1: {
        firstSemester: [6, 5, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [6, 6, 6],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
      2: {
        firstSemester: [4, 4, 5],
        firstSemesterGrade: 4,
        secondSemester: [5, 2, 6],
        secondSemesterGrade: 5,
        finalGrade: 5,
      },
      3: {
        firstSemester: [2, 3, 6, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [2, 2.5, 6, 6, 6],
        secondSemesterGrade: 4.5,
        finalGrade: 5,
      },
      4: {
        firstSemester: [6, 5.2, 5.5, 6],
        firstSemesterGrade: 6,
        secondSemester: [4.5, 5.5, 6, 6, 5.5],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
      5: {
        firstSemester: [6, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [6, 6, 6],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
    },
  },
  {
    name: "Georgi Georgiev",
    subjects: {
      0: {
        firstSemester: [4, 3, 4],
        firstSemesterGrade: 4,
        secondSemester: [5.2, 3, 4],
        secondSemesterGrade: 4,
        finalGrade: 4,
      },
      1: {
        firstSemester: [6, 6],
        firstSemesterGrade: 6,
        secondSemester: [5, 4, 5],
        secondSemesterGrade: 5,
        finalGrade: 5,
      },
      2: {
        firstSemester: [4, 3, 2, 4],
        firstSemesterGrade: 3,
        secondSemester: [5, 2, 6],
        secondSemesterGrade: 4,
        finalGrade: 4,
      },
      3: {
        firstSemester: [6, 2, 3],
        firstSemesterGrade: 4,
        secondSemester: [6, 6, 4],
        secondSemesterGrade: 5,
        finalGrade: 6,
      },
      4: {
        firstSemester: [5.5, 6],
        firstSemesterGrade: 6,
        secondSemester: [4.5, 5.5],
        secondSemesterGrade: 5,
        finalGrade: 5,
      },
      5: {
        firstSemester: [6, 2, 6],
        firstSemesterGrade: 5,
        secondSemester: [6, 2, 6],
        secondSemesterGrade: 4,
        finalGrade: 4,
      },
    },
  },
  {
    name: "Avgustin Petrov",
    subjects: {
      0: {
        firstSemester: [2, 3, 2],
        firstSemesterGrade: 2,
        secondSemester: [2, 3, 2],
        secondSemesterGrade: 2,
        finalGrade: 3,
      },
      1: {
        firstSemester: [2, 2.5, 3],
        firstSemesterGrade: 3,
        secondSemester: [3, 4, 2, 2],
        secondSemesterGrade: 2,
        finalGrade: 2,
      },
      2: {
        firstSemester: [2],
        firstSemesterGrade: 2,
        secondSemester: [2],
        secondSemesterGrade: 2,
        finalGrade: 2,
      },
      3: {
        firstSemester: [3],
        firstSemesterGrade: 3,
        secondSemester: [3],
        secondSemesterGrade: 3,
        finalGrade: 3,
      },
      4: {
        firstSemester: [2],
        firstSemesterGrade: 2,
        secondSemester: [2],
        secondSemesterGrade: 2,
        finalGrade: 6,
      },
      5: {
        firstSemester: [3, 3],
        firstSemesterGrade: 3,
        secondSemester: [2, 3],
        secondSemesterGrade: 3,
        finalGrade: 2,
      },
    },
  },
  {
    name: "Doroteya Lyubenova",
    subjects: {
      0: {
        firstSemester: [5, 6, 4, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [6, 6, 6],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
      1: {
        firstSemester: [6, 5, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [6, 6, 6],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
      2: {
        firstSemester: [4, 4, 5],
        firstSemesterGrade: 4,
        secondSemester: [5, 2, 6],
        secondSemesterGrade: 5,
        finalGrade: 5,
      },
      3: {
        firstSemester: [2, 3, 6, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [2, 2.5, 6, 6, 6],
        secondSemesterGrade: 4.5,
        finalGrade: 5,
      },
      4: {
        firstSemester: [6, 5.2, 5.5, 6],
        firstSemesterGrade: 6,
        secondSemester: [4.5, 5.5, 6, 6, 5.5],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
      5: {
        firstSemester: [6, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [6, 6, 6],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
    },
  },
];

export const stundets6b = [
  {
    name: "Gergana Petrova",
    subjects: {
      0: {
        firstSemester: [5, 6, 4, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [6, 6, 6],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
      1: {
        firstSemester: [6, 5, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [6, 6, 6],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
      2: {
        firstSemester: [4, 4, 5],
        firstSemesterGrade: 4,
        secondSemester: [5, 2, 6],
        secondSemesterGrade: 5,
        finalGrade: 5,
      },
      3: {
        firstSemester: [2, 3, 6, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [2, 2.5, 6, 6, 6],
        secondSemesterGrade: 4.5,
        finalGrade: 5,
      },
      4: {
        firstSemester: [6, 5.2, 5.5, 6],
        firstSemesterGrade: 6,
        secondSemester: [4.5, 5.5, 6, 6, 5.5],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
      5: {
        firstSemester: [6, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [6, 6, 6],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
    },
  },
  {
    name: "Georgi Georgiev",
    subjects: {
      0: {
        firstSemester: [4, 3, 4],
        firstSemesterGrade: 4,
        secondSemester: [5.2, 3, 4],
        secondSemesterGrade: 4,
        finalGrade: 4,
      },
      1: {
        firstSemester: [6, 6],
        firstSemesterGrade: 6,
        secondSemester: [5, 4, 5],
        secondSemesterGrade: 5,
        finalGrade: 5,
      },
      2: {
        firstSemester: [4, 3, 2, 4],
        firstSemesterGrade: 3,
        secondSemester: [5, 2, 6],
        secondSemesterGrade: 4,
        finalGrade: 4,
      },
      3: {
        firstSemester: [6, 2, 3],
        firstSemesterGrade: 4,
        secondSemester: [6, 6, 4],
        secondSemesterGrade: 5,
        finalGrade: 6,
      },
      4: {
        firstSemester: [5.5, 6],
        firstSemesterGrade: 6,
        secondSemester: [4.5, 5.5],
        secondSemesterGrade: 5,
        finalGrade: 5,
      },
      5: {
        firstSemester: [6, 2, 6],
        firstSemesterGrade: 5,
        secondSemester: [6, 2, 6],
        secondSemesterGrade: 4,
        finalGrade: 4,
      },
    },
  },
  {
    name: "Avgustin Petrov",
    subjects: {
      0: {
        firstSemester: [2, 3, 2],
        firstSemesterGrade: 2,
        secondSemester: [2, 3, 2],
        secondSemesterGrade: 2,
        finalGrade: 3,
      },
      1: {
        firstSemester: [2, 2.5, 3],
        firstSemesterGrade: 3,
        secondSemester: [3, 4, 2, 2],
        secondSemesterGrade: 2,
        finalGrade: 2,
      },
      2: {
        firstSemester: [2],
        firstSemesterGrade: 2,
        secondSemester: [2],
        secondSemesterGrade: 2,
        finalGrade: 2,
      },
      3: {
        firstSemester: [3],
        firstSemesterGrade: 3,
        secondSemester: [3],
        secondSemesterGrade: 3,
        finalGrade: 3,
      },
      4: {
        firstSemester: [2],
        firstSemesterGrade: 2,
        secondSemester: [2],
        secondSemesterGrade: 2,
        finalGrade: 6,
      },
      5: {
        firstSemester: [3, 3],
        firstSemesterGrade: 3,
        secondSemester: [2, 3],
        secondSemesterGrade: 3,
        finalGrade: 2,
      },
    },
  },
  {
    name: "Doroteya Lyubenova",
    subjects: {
      0: {
        firstSemester: [5, 6, 4, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [6, 6, 6],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
      1: {
        firstSemester: [6, 5, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [6, 6, 6],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
      2: {
        firstSemester: [4, 4, 5],
        firstSemesterGrade: 4,
        secondSemester: [5, 2, 6],
        secondSemesterGrade: 5,
        finalGrade: 5,
      },
      3: {
        firstSemester: [2, 3, 6, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [2, 2.5, 6, 6, 6],
        secondSemesterGrade: 4.5,
        finalGrade: 5,
      },
      4: {
        firstSemester: [6, 5.2, 5.5, 6],
        firstSemesterGrade: 6,
        secondSemester: [4.5, 5.5, 6, 6, 5.5],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
      5: {
        firstSemester: [6, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [6, 6, 6],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
    },
  },
];

export const stundets7g = [
  {
    name: "Ivanina Gospodinova",
    subjects: {
      0: {
        firstSemester: [5, 6, 4, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [6, 6, 6],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
      1: {
        firstSemester: [6, 5, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [6, 6, 6],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
      2: {
        firstSemester: [4, 4, 5],
        firstSemesterGrade: 4,
        secondSemester: [5, 2, 6],
        secondSemesterGrade: 5,
        finalGrade: 5,
      },
      3: {
        firstSemester: [2, 3, 6, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [2, 2.5, 6, 6, 6],
        secondSemesterGrade: 4.5,
        finalGrade: 5,
      },
      4: {
        firstSemester: [6, 5.2, 5.5, 6],
        firstSemesterGrade: 6,
        secondSemester: [4.5, 5.5, 6, 6, 5.5],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
      5: {
        firstSemester: [6, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [6, 6, 6],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
    },
  },
  {
    name: "Aleksandar Popov",
    subjects: {
      0: {
        firstSemester: [4, 3, 4],
        firstSemesterGrade: 4,
        secondSemester: [5.2, 3, 4],
        secondSemesterGrade: 4,
        finalGrade: 4,
      },
      1: {
        firstSemester: [6, 6],
        firstSemesterGrade: 6,
        secondSemester: [5, 4, 5],
        secondSemesterGrade: 5,
        finalGrade: 5,
      },
      2: {
        firstSemester: [4, 3, 2, 4],
        firstSemesterGrade: 3,
        secondSemester: [5, 2, 6],
        secondSemesterGrade: 4,
        finalGrade: 4,
      },
      3: {
        firstSemester: [6, 2, 3],
        firstSemesterGrade: 4,
        secondSemester: [6, 6, 4],
        secondSemesterGrade: 5,
        finalGrade: 6,
      },
      4: {
        firstSemester: [5.5, 6],
        firstSemesterGrade: 6,
        secondSemester: [4.5, 5.5],
        secondSemesterGrade: 5,
        finalGrade: 5,
      },
      5: {
        firstSemester: [6, 2, 6],
        firstSemesterGrade: 5,
        secondSemester: [6, 2, 6],
        secondSemesterGrade: 4,
        finalGrade: 4,
      },
    },
  },
  {
    name: "Dobri Petkov",
    subjects: {
      0: {
        firstSemester: [2, 3, 2],
        firstSemesterGrade: 2,
        secondSemester: [2, 3, 2],
        secondSemesterGrade: 2,
        finalGrade: 3,
      },
      1: {
        firstSemester: [2, 2.5, 3],
        firstSemesterGrade: 3,
        secondSemester: [3, 4, 2, 2],
        secondSemesterGrade: 2,
        finalGrade: 2,
      },
      2: {
        firstSemester: [2],
        firstSemesterGrade: 2,
        secondSemester: [2],
        secondSemesterGrade: 2,
        finalGrade: 2,
      },
      3: {
        firstSemester: [3],
        firstSemesterGrade: 3,
        secondSemester: [3],
        secondSemesterGrade: 3,
        finalGrade: 3,
      },
      4: {
        firstSemester: [2],
        firstSemesterGrade: 2,
        secondSemester: [2],
        secondSemesterGrade: 2,
        finalGrade: 6,
      },
      5: {
        firstSemester: [3, 3],
        firstSemesterGrade: 3,
        secondSemester: [2, 3],
        secondSemesterGrade: 3,
        finalGrade: 2,
      },
    },
  },
  {
    name: "Gergana Petrova",
    subjects: {
      0: {
        firstSemester: [5, 6, 4, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [6, 6, 6],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
      1: {
        firstSemester: [6, 5, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [6, 6, 6],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
      2: {
        firstSemester: [4, 4, 5],
        firstSemesterGrade: 4,
        secondSemester: [5, 2, 6],
        secondSemesterGrade: 5,
        finalGrade: 5,
      },
      3: {
        firstSemester: [2, 3, 6, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [2, 2.5, 6, 6, 6],
        secondSemesterGrade: 4.5,
        finalGrade: 5,
      },
      4: {
        firstSemester: [6, 5.2, 5.5, 6],
        firstSemesterGrade: 6,
        secondSemester: [4.5, 5.5, 6, 6, 5.5],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
      5: {
        firstSemester: [6, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [6, 6, 6],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
    },
  },
  {
    name: "Georgi Georgiev",
    subjects: {
      0: {
        firstSemester: [4, 3, 4],
        firstSemesterGrade: 4,
        secondSemester: [5.2, 3, 4],
        secondSemesterGrade: 4,
        finalGrade: 4,
      },
      1: {
        firstSemester: [6, 6],
        firstSemesterGrade: 6,
        secondSemester: [5, 4, 5],
        secondSemesterGrade: 5,
        finalGrade: 5,
      },
      2: {
        firstSemester: [4, 3, 2, 4],
        firstSemesterGrade: 3,
        secondSemester: [5, 2, 6],
        secondSemesterGrade: 4,
        finalGrade: 4,
      },
      3: {
        firstSemester: [6, 2, 3],
        firstSemesterGrade: 4,
        secondSemester: [6, 6, 4],
        secondSemesterGrade: 5,
        finalGrade: 6,
      },
      4: {
        firstSemester: [5.5, 6],
        firstSemesterGrade: 6,
        secondSemester: [4.5, 5.5],
        secondSemesterGrade: 5,
        finalGrade: 5,
      },
      5: {
        firstSemester: [6, 2, 6],
        firstSemesterGrade: 5,
        secondSemester: [6, 2, 6],
        secondSemesterGrade: 4,
        finalGrade: 4,
      },
    },
  },
  {
    name: "Avgustin Petrov",
    subjects: {
      0: {
        firstSemester: [2, 3, 2],
        firstSemesterGrade: 2,
        secondSemester: [2, 3, 2],
        secondSemesterGrade: 2,
        finalGrade: 3,
      },
      1: {
        firstSemester: [2, 2.5, 3],
        firstSemesterGrade: 3,
        secondSemester: [3, 4, 2, 2],
        secondSemesterGrade: 2,
        finalGrade: 2,
      },
      2: {
        firstSemester: [2],
        firstSemesterGrade: 2,
        secondSemester: [2],
        secondSemesterGrade: 2,
        finalGrade: 2,
      },
      3: {
        firstSemester: [3],
        firstSemesterGrade: 3,
        secondSemester: [3],
        secondSemesterGrade: 3,
        finalGrade: 3,
      },
      4: {
        firstSemester: [2],
        firstSemesterGrade: 2,
        secondSemester: [2],
        secondSemesterGrade: 2,
        finalGrade: 6,
      },
      5: {
        firstSemester: [3, 3],
        firstSemesterGrade: 3,
        secondSemester: [2, 3],
        secondSemesterGrade: 3,
        finalGrade: 2,
      },
    },
  },
  {
    name: "Doroteya Lyubenova",
    subjects: {
      0: {
        firstSemester: [5, 6, 4, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [6, 6, 6],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
      1: {
        firstSemester: [6, 5, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [6, 6, 6],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
      2: {
        firstSemester: [4, 4, 5],
        firstSemesterGrade: 4,
        secondSemester: [5, 2, 6],
        secondSemesterGrade: 5,
        finalGrade: 5,
      },
      3: {
        firstSemester: [2, 3, 6, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [2, 2.5, 6, 6, 6],
        secondSemesterGrade: 4.5,
        finalGrade: 5,
      },
      4: {
        firstSemester: [6, 5.2, 5.5, 6],
        firstSemesterGrade: 6,
        secondSemester: [4.5, 5.5, 6, 6, 5.5],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
      5: {
        firstSemester: [6, 6, 6],
        firstSemesterGrade: 6,
        secondSemester: [6, 6, 6],
        secondSemesterGrade: 6,
        finalGrade: 6,
      },
    },
  },
];
